env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  "no-restricted-syntax": ["error", "FunctionExpression", "WithStatement", "BinaryExpression[operator='in']"],
  'no-console': 0,
  'import/extensions': 0,
}
